### ISSUE TITLE
Export server: NullPointerExceptions when shutting down 

### ISSUE THREAD

**Issue by lpsnc** [highslide-software/highcharts.com#3785]
When shutting the export server we get several `NullPointerException`s

```
Feb 03, 2015 2:42:45 PM org.apache.coyote.http11.Http11Protocol destroy
INFO: Stopping Coyote HTTP/1.1 on http-11000
Exception in thread "Thread-11" java.lang.NullPointerException
        at com.highcharts.export.server.Server$1.run(Server.java:71)
Exception in thread "Thread-10" java.lang.NullPointerException
        at com.highcharts.export.server.Server$1.run(Server.java:71)
Exception in thread "Thread-9" java.lang.NullPointerException
Exception in thread "Thread-8"  at com.highcharts.export.server.Server$1.run(Server.java:71)
java.lang.NullPointerException
Exception in thread "Thread-12"         at com.highcharts.export.server.Server$1.run(Server.java:71)
java.lang.NullPointerException
        at com.highcharts.export.server.Server$1.run(Server.java:71)
```

**Comment by gvaartjes** [comment]
Could you tell me something about the platform and application server you're using?

**Comment by gvaartjes** [comment]
No repsonse from the user
