### ISSUE TITLE
v4.1.6 - Test provided within this library are not functioning at all

### ISSUE THREAD

**Issue by ptacekj** [highslide-software/highcharts.com#4304]
There is no way to test this library after making any sort of changes. It's not even possible to run `ant test-all` due to incorrect source file names and order. 

**Is this build target deprecated or have you started using some other testing method that I overlooked?**

To reproduce run 
```
ant test-all
```
output
```
test-specific-lib:
     [copy] Copying 1 file to /home/ptacekj/highcharts

replace-lib:

replace-adapter:
    [mkdir] Created dir: /home/ptacekj/highcharts/build/tests/jquery-1.7.2

set.properties:

run-test:
     [echo] /------------------------------------------------------------
     [echo]   Running unit tests using: jquery-1.7.2
     [echo]
     [echo]
     [java] setting runnermode QUIET
     [java] Configuration Error:
     [java] Cannot read [
     [java] /home/ptacekj/highcharts/js/parts/StackItem.js
     [java] ] derived from js/parts/StackItem.js
     [java] Java Result: 1
     [echo]
     [echo]
     [echo] \------------------------------------------------------------
```
For quick fix of test dependencies update `test/unit/jsTestDriver.conf` to contain:
```
server: http://localhost:4224

load:
# required libs, the first line is expanded to a specific library, dont change it.
#required.lib

# highcharts source, the first line is expanded to a specific adapter, dont change it.
#required.adapter
  - js/parts/Globals.js
  - js/parts/Utilities.js
  - js/parts/PathAnimation.js
  - js/parts/JQueryAdapter.js
  - js/parts/Adapters.js
  - js/parts/debug/EventMonitor.js
  - js/parts/Options.js
  - js/parts/Color.js
  - js/parts/SvgRenderer.js
  - js/parts/VmlRenderer.js
  - js/parts/CanVGRenderer.js
  - js/parts/Tick.js
  - js/parts/PlotLineOrBand.js
  - js/parts/Axis.js
  - js/parts/Point.js
  - js/parts/Tooltip.js
  - js/parts/Pointer.js
  - js/parts/Legend.js
  - js/parts/Chart.js
  - js/parts/Series.js
  - js/parts/LineSeries.js
  - js/parts/AreaSeries.js
  - js/parts/SplineSeries.js
  - js/parts/AreaSplineSeries.js
  - js/parts/ColumnSeries.js
  - js/parts/BarSeries.js
  - js/parts/ScatterSeries.js
  - js/parts/CenteredSeriesMixin.js
  - js/parts/PieSeries.js
  - js/parts/DataGrouping.js
  - js/parts/Stacking.js
  - js/parts/Facade.js

# tests
  - test/unit/ColorTest.js
  - test/unit/DataGroupingTest.js
  - test/unit/UtilitiesTest.js
  - test/unit/TooltipTest.js
  - test/unit/AdaptersTest.js
  - test/unit/RendererTest.js
  - test/unit/AxisTest.js
  - test/unit/IssuesTest.js
```
and run 
```
ant test-all
```
to get 
```
test-specific-lib:
     [copy] Copying 1 file to /home/ptacekj/projects/highcharts-sbks

replace-lib:

replace-adapter:
    [mkdir] Created dir: /home/ptacekj/highcharts/build/tests/jquery-1.8.0

set.properties:

run-test:
     [echo] /------------------------------------------------------------
     [echo]   Running unit tests using: jquery-1.8.0
     [echo]
     [echo]
     [java] setting runnermode QUIET
     [java] Chrome: Reset
     [java] Chrome: Reset
     [java] F............F.......E..F..........................E..E.
     [java] Total 56 tests (Passed: 50; Fails: 3; Errors: 3) (133.00 ms)
     [java]   Chrome 43.0.2357.124 Windows: Run 56 tests (Passed: 50; Fails: 3; Errors 3) (133.00 ms)
     [java]     ColorTest.testConstruction failed (12.00 ms): AssertError: 4 methods. expected 4 but was 5
     [java]       AssertError: 4 methods. expected 4 but was 5
     [java]           at ColorTest.testConstruction (http://localhost:4224/test/test/unit/ColorTest.js:13:42)
     [java]
     [java]     UtilitiesTest.testIsObject failed (4.00 ms): AssertError: IsObject undefined expected false but was [undefined]
     [java]       AssertError: IsObject undefined expected false but was [undefined]
     [java]           at UtilTest.testIsObject (http://localhost:4224/test/test/unit/UtilitiesTest.js:72:53)
     [java]
     [java]     UtilitiesTest.testNumberFormat error (1.00 ms): ReferenceError: numberFormat is not defined
     [java]       ReferenceError: numberFormat is not defined
     [java]           at UtilTest.testNumberFormat (http://localhost:4224/test/test/unit/UtilitiesTest.js:240:48)
     [java]
     [java]     TooltipTest.testGetPosition failed (6.00 ms): AssertError: TopRight rectInRect chart expected true but was false
     [java]       AssertError: TopRight rectInRect chart expected true but was false
     [java]           at TooltipTest.testGetPosition (http://localhost:4224/test/test/unit/TooltipTest.js:104:47)
     [java]
     [java]     RendererTest.testCssFontSize error (2.00 ms): TypeError: Cannot read property 'fontSize' of undefined
     [java]       TypeError: Cannot read property 'fontSize' of undefined
     [java]           at RendererTest.testCssFontSize (http://localhost:4224/test/test/unit/RendererTest.js:29:47)
     [java]
     [java]     AxisTest.testToPixelsAndValues error (36.00 ms): TypeError: this.getLogTickPositions is not a function
     [java]       TypeError: this.getLogTickPositions is not a function
     [java]           at Object.Axis.setTickPositions (http://localhost:4224/test/js/parts/Axis.js:1067:26)
     [java]           at Object.Axis.setTickInterval (http://localhost:4224/test/js/parts/Axis.js:1027:8)
     [java]           at Object.Axis.setScale (http://localhost:4224/test/js/parts/Axis.js:1271:9)
     [java]           at Object.<anonymous> (http://localhost:4224/test/js/parts/DataGrouping.js:490:10)
     [java]           at Object.obj.(anonymous function) [as setScale] (http://localhost:4224/test/js/parts/Utilities.js:280:15)
     [java]           at http://localhost:4224/test/js/parts/Chart.js:1181:9
     [java]           at Array.forEach (native)
     [java]           at each.Array.forEach.len (http://localhost:4224/test/js/parts/JQueryAdapter.js:97:37)
     [java]           at Object.Chart.render (http://localhost:4224/test/js/parts/Chart.js:1180:8)
     [java]           at Object.Chart.firstRender (http://localhost:4224/test/js/parts/Chart.js:1392:9)
     [java]
     [echo]
     [echo]
     [echo] \------------------------------------------------------------
```

**Comment by highslide-software** [comment]
We're not using jsTestRunner anymore.
