### ISSUE TITLE
HighStock: Tooltip Error, Point has no Series

### ISSUE THREAD

**Issue by NathanWolf** [highslide-software/highcharts.com#4630]
We've run into a randomly-occuring error since migrating to HighStock, I don't believe we saw the issue in HighCharts. We are on 2.1.8, and migrated from HighCharts 4.0.4 so it may also be a version difference, but I have not done testing on Highcharts 4.1.8 to know for sure.

The error presents as

```
TypeError: Cannot read property 'tooltipOptions' of null
    at Object.Tooltip.refresh (highstock.src.js:9250:49)
    at Object.Pointer.runPointActions (highstock.src.js:9648:14)
    at Object.Pointer.onContainerMouseMove (highstock.src.js:10019:9)
    at HTMLDivElement.container.onmousemove (highstock.src.js:10106:12)
```

I have tried to debug it a bit, but I've only been able to determine that it appears there is a point without a series assigned to it ending up in the collection of nearest points presented to the tooltip.

I suspect it may be an edge case when removing a series while the tooltip is calculating, but I have not yet been able to put together a reliable reproduction case. I will keep trying and report back. I am also looking to find a workaround, it is such a random and infrequent issue that it's been hard to pin down.

**Comment by NathanWolf** [comment]
My apologies, on further investigation this looks like it was caused by an extension we were using (legend-extension.js). I'm going to close this unless I see the issue again in a different context.

Thank you for your time!
